Add feature "sort"
netconf-wg/list-pagination pull request #29
Opened 2024-11-22 09:48 UTC by avtobiff

This feature indicates support for "locale", "sort-by", and "direction".

Fixes: #28

2024-11-22 11:23 UTC, kwatsen requested changes
we need to discuss

2025-02-06 16:45 UTC, avtobiff commented
The "direction" query parameter should be in the required set to implement.

2025-02-06 17:44 UTC, kwatsen requested changes

2025-02-06 17:44 UTC, kwatsen commented on ietf-list-pagination.yang
> +       and "direction" are supported.';
This line needs to be updated too.

2025-02-06 17:44 UTC, kwatsen commented on ietf-list-pagination.yang
> +    if-feature "sort";
Not specific to this line, my comment applies to other `if-feature` statements as well:

Should `sort` be in double-quotes?

2025-02-07 10:13 UTC, avtobiff commented on ietf-list-pagination.yang
> +    if-feature "sort";
In RFC 7950 complex if-feature statements are double quoted
and simple (i.e. single word) are not.

In RFC 8639 simple if-feature statements are double quoted
FWIW.

Should the double quotes be removed?

I don't have a strong opinion.

2025-02-26 21:23 UTC, kwatsen commented on ietf-list-pagination.yang
> +    if-feature "sort";
no strong opinion either.  I only noticed it due to the syntax highlighting color-coding the inconsistency.  That is, the feature statements as a collection vary the approach used.

2025-03-03 20:50 UTC, merged